@startuml
'https://plantuml.com/sequence-diagram

class User {
    - username : String
    - password : String
    - coins: double
    - stack: Stack
    - deck: Deck
    - profile: Profile
    + void tradeCard(Card card, Requirement requirement)
    + void buyPackage(Package newPackage)
    + void selectBestCards()
    + void register()
    + void login()
    + void viewScores()
    + void viewProfile()
    + void editProfile()
}

class Profile {
    - name : String
    - email : String
    - otherDetails : String
    + void displayProfile()
    + void updateStatus()
}

class Card {
    # name : String
    # damage : Integer
    # elementType: String
    + void getAttributes()
    + void displayCardInfo()
    + void upgradeCard()
}

class SpellCard {
    + void castSpell()
    + void calculateEffectiveDamage(ElementType opponentElementType)
}

class MonsterCard {
    + void evolve()
    + void reproduce()
    + void calculateEffectiveDamage(ElementType opponentElementType)
}

class Stack{
    - stackCards: Card[]
    + void removeCard(Card card)
    + void attainCard(Card card)
    + void shuffleCards()
    + void organizeByElement()
}

class Package {
    - packageCards: Card[5]
    + void openPackage()
    + void displayPackageInfo()
    + void applyDiscount()
}

class Deck {
    - bestCards: Card[4]
    + void addCardToDeck(Card card)
    + void removeCardFromDeck(Card card)
    + void reorganizeDeck()
}

enum ElementType {
    WATER
    FIRE
    NORMAL
}

class Requirement {
    - cardType: CardType
    - minDamage: Integer
    + satisfiesRequirement(Card card)
}

enum CardType {
    MONSTER
    SPELL
}

class Battle {
    - user1: User
    - user2: User
    + void startBattle()
    + void endBattle()
    + void displayBattleResults()
}

class GameController {
    - users: User[]
    - battles: Battle[]
    + void createUser(String username, String password)
    + void initiateBattle(User user1, User user2)
}

Card <|-- MonsterCard
Card <|-- SpellCard

User "1" -- "1..*" Card : owns
User "1" -- "1" Deck : has
User "1" -- "1..*" Package : canAcquire
User "1" -- "1" Stack : has
User "1" -- "1" Profile : has

Stack "1" o-- "1..*" Card : contains
Package "1" o-- "1..*" Card : contains
Deck "1" o-- "1..*" Card : contains

Battle "1" o-- "*" Deck : isFoughtWith
Battle "1" o-- "2" User : isFoughtBy

GameController "1" o-- "1..*" User : manages
GameController "1" o-- "1..*" Battle : manages

@enduml
